### ISSUE TITLE
https://api.tiktokv.com/aweme/v1 Empty response body

### ISSUE THREAD

**Issue by TheBunnies** [tahaluindo/Tiktok-ViewsBOT#1]
Good evening!

It apperears that `https://api.tiktokv.com/aweme/v1/multi/aweme/detail/?aweme_ids={id}` does not longer work. Tried to get a response multiple times with different IP addresses. But every request seems to result in the same response: **200 OK** and an empty response body.

**Comment by tahaluindo** [comment]
OK
