### ISSUE TITLE
AttributeError : 'NoneType'

### ISSUE THREAD

**Issue by bens106** [tahaluindo/Tiktok-ViewsBOT#9]
zefoy.py line 320
zefoy.py line 46
inject.get_sesion_captcha()
process.py line 71
in get_session_captcha
url=self.API_ZEFOY + soup.find('img' 

AttributeError: 'NoneType' object has no attribute 'get'

**Comment by tahaluindo** [comment]
`git pull` end next command
```bash
python barubang.py
```
